"""Google Colab backend — generates self-contained Colab notebooks from recipes."""
from __future__ import annotations

import json
import os
import textwrap
import uuid
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel

from kdream.backends.base import AbstractBackend
from kdream.core.recipe import Recipe
from kdream.exceptions import BackendError

console = Console()


# ---------------------------------------------------------------------------
# Notebook builder
# ---------------------------------------------------------------------------

class NotebookBuilder:
    """Builds a self-contained Jupyter/Colab notebook from a kdream recipe."""

    _GPU_CHECK = textwrap.dedent("""\
        import subprocess

        result = subprocess.run(["nvidia-smi"], capture_output=True)
        if result.returncode == 0:
            print("\\u2713 GPU runtime detected")
            print(result.stdout.decode()[:500])
        else:
            print("\\u26a0 No GPU detected \\u2014 running on CPU.")
            print("Tip: Runtime \\u2192 Change runtime type \\u2192 T4 GPU for best performance.")
    """)

    def build(self, recipe: Recipe, inputs: dict[str, Any] | None = None) -> dict:
        """Return a complete notebook dict (ready to be serialised as .ipynb)."""
        cells: list[dict] = [
            self._markdown_cell(
                f"# {recipe.metadata.name}\n\n"
                f"{recipe.metadata.description}\n\n"
                f"**Tags:** {', '.join(recipe.metadata.tags)}  \n"
                f"**License:** {recipe.metadata.license}  \n"
                f"**Generated by:** [kdream](https://github.com/ismaelfaro/kdreams)\n"
            ),
            self._code_cell(self._GPU_CHECK, cell_id="hardware_check"),
            self._code_cell(self._clone_code(recipe), cell_id="clone_repo"),
            self._code_cell(self._deps_code(recipe), cell_id="install_deps"),
        ]

        if recipe.models:
            cells.append(self._code_cell(self._models_code(recipe), cell_id="download_models"))

        cells.append(
            self._code_cell(self._inputs_code(recipe, inputs or {}), cell_id="set_inputs")
        )
        cells.append(self._code_cell(self._run_code(recipe), cell_id="run_inference"))
        cells.append(self._code_cell(self._outputs_code(recipe), cell_id="show_outputs"))

        return {
            "nbformat": 4,
            "nbformat_minor": 0,
            "metadata": {
                "colab": {
                    "name": f"kdream-{recipe.metadata.name}.ipynb",
                    "provenance": [],
                    "gpuType": "T4",
                },
                "accelerator": "GPU",
                "kernelspec": {"name": "python3", "display_name": "Python 3"},
                "language_info": {"name": "python"},
            },
            "cells": cells,
        }

    # ------------------------------------------------------------------
    # Cell helpers
    # ------------------------------------------------------------------

    def _markdown_cell(self, source: str) -> dict:
        return {
            "cell_type": "markdown",
            "metadata": {"id": _uid()},
            "source": source,
        }

    def _code_cell(self, source: str, cell_id: str | None = None) -> dict:
        return {
            "cell_type": "code",
            "metadata": {"id": cell_id or _uid()},
            "source": source,
            "execution_count": None,
            "outputs": [],
        }

    # ------------------------------------------------------------------
    # Source generators
    # ------------------------------------------------------------------

    def _clone_code(self, recipe: Recipe) -> str:
        repo = recipe.source.repo
        ref = recipe.source.ref or "main"
        name = recipe.metadata.name
        return textwrap.dedent(f"""\
            import os, subprocess

            REPO_URL = {repo!r}
            REF = {ref!r}
            WORK_DIR = f"/content/{name}"

            if not os.path.exists(WORK_DIR):
                subprocess.run(
                    ["git", "clone", "--depth", "1", "--branch", REF, REPO_URL, WORK_DIR],
                    check=True,
                )
            else:
                print(f"Repository already cloned at {{WORK_DIR}}")

            os.chdir(WORK_DIR)
            print(f"Working directory: {{os.getcwd()}}")
        """)

    def _deps_code(self, recipe: Recipe) -> str:
        extras = recipe.source.install_extras
        extras_joined = ",".join(extras)
        lines: list[str] = [
            "import subprocess, sys, os",
            "",
            "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'uv'], check=True)",
            "",
        ]
        if recipe.source.skip_package_install:
            lines.append("print('Package install skipped (skip_package_install=true)')")
        else:
            lines += [
                "for req_file in ['requirements.txt', 'requirements/base.txt',"
                " 'requirements/main.txt']:",
                "    if os.path.exists(req_file):",
                "        subprocess.run(",
                "            [sys.executable, '-m', 'uv', 'pip', 'install', '-q',"
                " '-r', req_file],",
                "            check=True,",
                "        )",
                "        break",
                "",
                "if os.path.exists('pyproject.toml') or os.path.exists('setup.py'):",
                f"    extra = '[{extras_joined}]' if {extras_joined!r} else ''",
                "    subprocess.run(",
                "        [sys.executable, '-m', 'uv', 'pip', 'install', '-q',"
                " '-e', f'.{extra}'],",
                "        check=True,",
                "    )",
                "",
                "print('\\u2713 Dependencies installed')",
            ]
        return "\n".join(lines)

    def _models_code(self, recipe: Recipe) -> str:
        lines: list[str] = [
            "from pathlib import Path",
            "",
            "MODELS_DIR = Path('/content/models')",
            "MODELS_DIR.mkdir(parents=True, exist_ok=True)",
            "",
        ]
        for model in recipe.models:
            dest_expr = f"MODELS_DIR / {model.destination!r}"
            if model.source == "huggingface":
                lines += [
                    f"# Download model: {model.name}",
                    "try:",
                    "    from huggingface_hub import snapshot_download",
                    f"    snapshot_download(",
                    f"        repo_id={model.id!r},",
                    f"        local_dir={dest_expr},",
                    "        ignore_patterns=['*.msgpack', '*.h5', 'flax_model*'],",
                    "    )",
                    f"    print('\\u2713 Downloaded {model.id}')",
                    "except Exception as _e:",
                    f"    print(f'\\u26a0 Failed to download {model.id}: {{_e}}')",
                    "",
                ]
            elif model.source == "url":
                lines += [
                    f"# Download model: {model.name}",
                    "import urllib.request",
                    f"_dest = {dest_expr} / Path({model.id!r}).name",
                    "_dest.parent.mkdir(parents=True, exist_ok=True)",
                    "if not _dest.exists():",
                    f"    print('Downloading {model.name}...')",
                    f"    urllib.request.urlretrieve({model.id!r}, _dest)",
                    f"    print('\\u2713 Downloaded {model.name}')",
                    "else:",
                    f"    print('\\u2713 {model.name} already present')",
                    "",
                ]
            elif model.source == "civitai":
                lines += [
                    f"# CivitAI model: {model.name}",
                    "import urllib.request, os",
                    "_token = os.environ.get('CIVITAI_TOKEN', '')",
                    "_headers = {'Authorization': f'Bearer {{_token}}'} if _token else {}",
                    f"_url = f'https://civitai.com/api/download/models/{model.id}'",
                    f"_dest = {dest_expr} / '{model.name}.safetensors'",
                    "_dest.parent.mkdir(parents=True, exist_ok=True)",
                    "if not _dest.exists():",
                    "    _req = urllib.request.Request(_url, headers=_headers)",
                    "    with urllib.request.urlopen(_req) as _r, open(_dest, 'wb') as _f:",
                    "        _f.write(_r.read())",
                    f"    print('\\u2713 Downloaded {model.name}')",
                    "",
                ]
        lines.append("print('\\u2713 All models ready')")
        return "\n".join(lines)

    def _inputs_code(self, recipe: Recipe, inputs: dict[str, Any]) -> str:
        lines: list[str] = [
            "# ── Inference inputs ─────────────────────────────────────────",
            "# Edit these values before running the inference cell.",
            "",
        ]
        for name, spec in recipe.inputs.items():
            raw = inputs.get(name)
            if raw is None:
                raw = spec.default
            comment = f"  # {spec.description}" if spec.description else ""
            if spec.type == "string":
                val_repr = repr(str(raw)) if raw is not None else '""'
            elif spec.type in ("integer", "float"):
                val_repr = str(raw) if raw is not None else "0"
            elif spec.type == "boolean":
                val_repr = "True" if raw else "False"
            else:
                val_repr = repr(raw) if raw is not None else "None"
            lines.append(f"{name} = {val_repr}{comment}")
        return "\n".join(lines)

    def _run_code(self, recipe: Recipe) -> str:
        script = recipe.entrypoint.script
        entry_type = recipe.entrypoint.type
        name = recipe.metadata.name
        arg_mapping = recipe.entrypoint.args_mapping or {}

        lines: list[str] = [
            "import subprocess, sys, os",
            "",
            f"WORK_DIR = '/content/{name}'",
            "os.chdir(WORK_DIR)",
            "",
        ]

        if entry_type == "gradio":
            lines += [
                "# Gradio app — launch and wait for the public URL",
                "import time",
                f"_proc = subprocess.Popen([sys.executable, {script!r}],",
                "                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT)",
                "time.sleep(8)",
                "for _line in iter(_proc.stdout.readline, b''):",
                "    _dec = _line.decode()",
                "    if 'gradio.live' in _dec or 'running on' in _dec.lower():",
                "        print('Gradio URL:', _dec.strip())",
                "        break",
            ]
        else:
            lines.append(f"_cmd = [sys.executable, f'{{WORK_DIR}}/{script}']")
            for inp_name, spec in recipe.inputs.items():
                flag = arg_mapping.get(inp_name, inp_name.replace("_", "-"))
                if spec.type == "boolean":
                    lines += [
                        f"if {inp_name}:",
                        f"    _cmd += ['--{flag}']",
                    ]
                else:
                    lines.append(f"_cmd += ['--{flag}', str({inp_name})]")
            lines += [
                "",
                "print('Running:', ' '.join(_cmd[:5]), '...')",
                "_result = subprocess.run(_cmd, capture_output=True, text=True, cwd=WORK_DIR)",
                "print(_result.stdout[-3000:] if _result.stdout else '')",
                "if _result.returncode != 0:",
                "    print('STDERR:', _result.stderr[-2000:])",
                "    raise RuntimeError(f'Inference failed (exit {_result.returncode})')",
                "print('\\u2713 Inference complete')",
            ]
        return "\n".join(lines)

    def _outputs_code(self, recipe: Recipe) -> str:
        if not recipe.outputs:
            return "print('No outputs defined in recipe.')"

        lines: list[str] = ["import glob"]
        _ext_media = {
            ".png": "image", ".jpg": "image", ".jpeg": "image",
            ".gif": "image", ".webp": "image",
            ".mp4": "video", ".webm": "video",
            ".wav": "audio", ".mp3": "audio", ".flac": "audio",
        }

        for out in recipe.outputs:
            path_pat = out.path or ""
            ext = Path(path_pat).suffix.lower() if path_pat else ""
            media = _ext_media.get(ext, "file")

            lines += [
                f"# Output: {out.name}",
                f"_files = sorted(glob.glob('outputs/*{ext}') +"
                f" glob.glob('/content/{recipe.metadata.name}/outputs/*{ext}'))",
                "if _files:",
                "    _latest = _files[-1]",
                "    print(f'Output: {{_latest}}')",
            ]
            if media == "image":
                lines += [
                    "    from IPython.display import Image, display",
                    "    display(Image(filename=_latest))",
                ]
            elif media == "audio":
                lines += [
                    "    from IPython.display import Audio, display",
                    "    display(Audio(filename=_latest))",
                ]
            elif media == "video":
                lines += [
                    "    from IPython.display import HTML, display",
                    "    display(HTML(f'<video controls width=640>"
                    "<source src=\"{_latest}\"></video>'))",
                ]
            lines += ["else:", f"    print('No output found for {out.name}')", ""]

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Google Drive uploader (optional)
# ---------------------------------------------------------------------------

class GoogleDriveUploader:
    """Upload notebooks to Google Drive and return a Colab URL."""

    SCOPES = ["https://www.googleapis.com/auth/drive.file"]

    def __init__(self, credentials_path: str):
        self.credentials_path = credentials_path

    def upload(self, notebook_path: Path, name: str) -> str:
        """Upload *notebook_path* to Drive and return the Colab open URL."""
        try:
            from google.oauth2 import service_account  # type: ignore[import]
            from googleapiclient.discovery import build  # type: ignore[import]
            from googleapiclient.http import MediaFileUpload  # type: ignore[import]
        except ImportError:
            raise BackendError(
                "Google Drive upload requires 'google-auth' and 'google-api-python-client'.\n"
                "Install them with: pip install 'kdream[colab]'"
            )

        creds = service_account.Credentials.from_service_account_file(
            self.credentials_path, scopes=self.SCOPES
        )
        service = build("drive", "v3", credentials=creds)

        file_meta = {
            "name": name,
            "mimeType": "application/vnd.google.colaboratory",
        }
        media = MediaFileUpload(str(notebook_path), mimetype="application/json")
        uploaded = (
            service.files()
            .create(body=file_meta, media_body=media, fields="id")
            .execute()
        )
        file_id = uploaded["id"]
        # Make publicly viewable so anyone with the link can open it
        service.permissions().create(
            fileId=file_id,
            body={"type": "anyone", "role": "reader"},
        ).execute()

        return f"https://colab.research.google.com/drive/{file_id}"


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _uid() -> str:
    return uuid.uuid4().hex[:12]


def _colab_github_url(recipe: Recipe) -> str | None:
    """Build a colab.research.google.com/github/… URL when the recipe's repo
    is on GitHub and the notebook is committed there."""
    repo = recipe.source.repo or ""
    if "github.com" not in repo:
        return None
    gh_path = repo.removeprefix("https://").removeprefix("github.com/").strip("/")
    ref = recipe.source.ref or "main"
    nb_path = f"kdream/recipes/notebooks/{recipe.metadata.name}.ipynb"
    return f"https://colab.research.google.com/github/{gh_path}/blob/{ref}/{nb_path}"


# ---------------------------------------------------------------------------
# Backend
# ---------------------------------------------------------------------------

class ColabBackend(AbstractBackend):
    """Google Colab compute backend.

    Generates a self-contained Jupyter notebook from a kdream recipe that can
    be opened directly in Google Colab. The notebook handles:

    * GPU runtime detection
    * Repository cloning and dependency installation (via ``uv``)
    * Model downloading (HuggingFace Hub, direct URL, CivitAI)
    * Parameterised inference with pre-filled input values
    * Output display (images via IPython.display, audio, video)

    If ``gdrive_credentials`` (or the ``KDREAM_GDRIVE_CREDENTIALS`` env var) is
    set to the path of a Google service-account JSON key, the notebook is
    uploaded to Drive and a direct Colab URL is printed automatically.

    Usage::

        kdream install stable-diffusion-xl-base --backend colab
        kdream run stable-diffusion-xl-base --backend colab --prompt "red panda"
    """

    name = "colab"

    def __init__(
        self,
        gdrive_credentials: str | None = None,
        verbose: bool = False,
    ):
        self.gdrive_credentials = gdrive_credentials or os.environ.get(
            "KDREAM_GDRIVE_CREDENTIALS"
        )
        self.verbose = verbose
        self._builder = NotebookBuilder()

    # ------------------------------------------------------------------
    # AbstractBackend interface
    # ------------------------------------------------------------------

    def install(
        self,
        recipe: Recipe,
        cache_dir: Path,
        force_reinstall: bool = False,
    ):
        """Generate the base Colab notebook and save it to the cache directory.

        No network calls are made during install — model downloads happen inside
        the notebook when the user opens it in Colab.

        Returns:
            :class:`~kdream.core.runner.PackageInfo` with ``path`` pointing to
            the directory containing the generated notebook.
        """
        from kdream.core.runner import PackageInfo

        pkg_dir = cache_dir / recipe.metadata.name
        nb_dir = pkg_dir / "colab"
        nb_dir.mkdir(parents=True, exist_ok=True)
        nb_path = nb_dir / f"kdream-{recipe.metadata.name}.ipynb"

        if nb_path.exists() and not force_reinstall:
            console.print(
                f"  [dim]Notebook already generated: {nb_path}[/dim]\n"
                "  Use --force-reinstall to regenerate."
            )
        else:
            console.print(
                f"\n[bold][1/1][/bold] Generating Colab notebook for "
                f"[cyan]{recipe.metadata.name}[/cyan]…"
            )
            notebook = self._builder.build(recipe)
            nb_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
            console.print(f"  [green]✓ Notebook saved:[/green] {nb_path}")

        return PackageInfo(
            recipe_name=recipe.metadata.name,
            path=nb_dir,
            ready=nb_path.exists(),
            venv_path=nb_dir,
            repo_path=nb_dir,
            models_path=nb_dir,
        )

    def run(self, package, inputs: dict[str, Any]) -> dict[str, Any]:
        """Inject *inputs* into the notebook and provide a Colab URL.

        Generates a run-specific notebook with input values pre-filled, then:
        * Uploads to Google Drive (if credentials configured) and returns a URL.
        * Falls back to printing manual upload instructions.

        Returns:
            Dict with keys ``notebook_path``, ``colab_url``, and ``instructions``.
        """
        nb_base = package.path / f"kdream-{package.recipe_name}.ipynb"
        if not nb_base.exists():
            raise BackendError(
                f"Colab notebook not found at {nb_base}. "
                "Run 'kdream install --backend colab <recipe>' first."
            )

        # Load recipe for input injection
        recipe_file = nb_base.parent.parent / "kdream-recipe.yaml"
        recipe: Recipe | None = None
        if recipe_file.exists():
            from kdream.core.recipe import load_recipe
            recipe = load_recipe(str(recipe_file))
        else:
            try:
                from kdream.core.registry import RegistryClient
                recipe = RegistryClient().fetch_recipe(package.recipe_name)
            except Exception:
                pass

        # Generate run-specific notebook with inputs injected
        nb_run_path = nb_base.parent / f"kdream-{package.recipe_name}-run.ipynb"
        if recipe is not None:
            notebook = self._builder.build(recipe, inputs)
            nb_run_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
        else:
            import shutil
            shutil.copy2(str(nb_base), str(nb_run_path))

        colab_url = self._resolve_colab_url(recipe, nb_run_path)

        # User-facing instructions
        if colab_url:
            url_section = (
                f"[bold green]Open in Colab:[/bold green]\n[link]{colab_url}[/link]"
            )
        else:
            url_section = (
                "To run in Colab:\n"
                "1. Go to [link]https://colab.research.google.com[/link]\n"
                "2. File \u2192 Upload notebook \u2192 select the file above\n"
                "3. Runtime \u2192 Run all  (Ctrl+F9)\n\n"
                "[dim]Tip: set KDREAM_GDRIVE_CREDENTIALS to a service-account JSON\n"
                "for automatic Drive upload and direct Colab URLs.[/dim]"
            )

        console.print(Panel(
            f"[bold]Colab Notebook Ready[/bold]\n\n"
            f"Notebook: [cyan]{nb_run_path}[/cyan]\n\n"
            + url_section,
            title="kdream Colab",
            expand=False,
        ))

        return {
            "notebook_path": str(nb_run_path),
            "colab_url": colab_url or "",
            "instructions": (
                f"Open in Colab: {colab_url}"
                if colab_url else
                f"Upload {nb_run_path} to Google Colab to run inference."
            ),
        }

    def is_installed(self, recipe_name: str, cache_dir: Path) -> bool:
        """Return True if the Colab notebook has already been generated."""
        nb_path = cache_dir / recipe_name / "colab" / f"kdream-{recipe_name}.ipynb"
        return nb_path.exists()

    def generate_notebook(
        self,
        recipe: Recipe,
        inputs: dict[str, Any] | None = None,
        output_path: str | None = None,
    ) -> Path:
        """Generate a Colab notebook for *recipe* and save it.

        Convenience method for use outside the install/run flow
        (e.g. from the CLI or scripts).

        Args:
            recipe:      Recipe to generate the notebook from.
            inputs:      Optional input values to pre-fill.
            output_path: Where to save the file (defaults to cwd).

        Returns:
            Path to the saved ``.ipynb`` file.
        """
        notebook = self._builder.build(recipe, inputs or {})
        dest = Path(output_path) if output_path else (
            Path.cwd() / f"kdream-{recipe.metadata.name}.ipynb"
        )
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
        return dest

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _resolve_colab_url(self, recipe: Recipe | None, nb_path: Path) -> str | None:
        """Try to obtain a usable Colab URL for the notebook.

        Priority:
        1. Upload to Google Drive (if credentials configured).
        2. Build a GitHub Colab URL (if recipe source is on GitHub).
        3. Return ``None`` — manual upload required.
        """
        if self.gdrive_credentials:
            try:
                url = GoogleDriveUploader(self.gdrive_credentials).upload(nb_path, nb_path.name)
                console.print("  [green]✓ Uploaded to Google Drive[/green]")
                return url
            except BackendError as exc:
                console.print(f"  [yellow]⚠ Drive upload failed:[/yellow] {exc}")
            except Exception as exc:
                if self.verbose:
                    console.print(f"  [dim]Drive upload error: {exc}[/dim]")

        if recipe is not None:
            return _colab_github_url(recipe)

        return None
