"""RunPod.io backend — serverless endpoint deployment via Docker images."""
from __future__ import annotations

import json
import os
import textwrap
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel

from kdream.backends.base import AbstractBackend
from kdream.core.recipe import Recipe
from kdream.exceptions import BackendError

console = Console()


# ---------------------------------------------------------------------------
# Dockerfile builder
# ---------------------------------------------------------------------------

class DockerfileBuilder:
    """Generates a Dockerfile for a RunPod serverless endpoint."""

    BASE_IMAGE = "runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04"

    def build(self, recipe: Recipe, skip_package_install: bool = False) -> str:
        """Return Dockerfile content string for *recipe*."""
        name = recipe.metadata.name
        repo = recipe.source.repo
        ref = recipe.source.ref or "main"
        extras = recipe.source.install_extras
        extras_joined = ",".join(extras)
        extra_suffix = f"[{extras_joined}]" if extras_joined else ""

        lines: list[str] = [
            f"FROM {self.BASE_IMAGE}",
            "",
            "# Environment",
            "ENV HF_HOME=/runpod-volume/.cache/huggingface \\",
            "    PYTHONUNBUFFERED=1 \\",
            "    MODELS_DIR=/runpod-volume/models \\",
            "    DEBIAN_FRONTEND=noninteractive",
            "",
            "# System deps",
            "RUN apt-get update -qq && apt-get install -y -q git curl && rm -rf /var/lib/apt/lists/*",
            "",
            "# Install uv",
            "RUN pip install --quiet uv",
            "",
            f"# Clone recipe source",
            f"RUN git clone --depth 1 --branch {ref} {repo} /workspace/{name}",
            "",
        ]

        if not skip_package_install:
            lines += [
                "# Install Python dependencies",
                f"WORKDIR /workspace/{name}",
                "RUN if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; \\",
                "    elif [ -f requirements/base.txt ]; then uv pip install --system -r requirements/base.txt; \\",
                "    elif [ -f requirements/main.txt ]; then uv pip install --system -r requirements/main.txt; fi",
                f"RUN if [ -f pyproject.toml ] || [ -f setup.py ]; then uv pip install --system -e '.{extra_suffix}'; fi",
                "",
            ]
        else:
            lines += [
                f"WORKDIR /workspace/{name}",
                "",
            ]

        lines += [
            "# Install runpod SDK",
            "RUN pip install --quiet runpod",
            "",
            "# Copy serverless handler",
            "COPY handler.py /workspace/handler.py",
            "",
            f"WORKDIR /workspace/{name}",
            "",
            'CMD ["python", "/workspace/handler.py"]',
        ]

        return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Handler builder
# ---------------------------------------------------------------------------

class HandlerBuilder:
    """Generates handler.py — the RunPod serverless worker script."""

    def build(self, recipe: Recipe) -> str:
        """Return handler.py content string for *recipe*."""
        name = recipe.metadata.name
        script = recipe.entrypoint.script
        arg_mapping = recipe.entrypoint.args_mapping or {}
        has_models = bool(recipe.models)

        lines: list[str] = [
            "# Auto-generated by kdream — RunPod serverless handler",
            "from __future__ import annotations",
            "import os, subprocess, sys",
            "from pathlib import Path",
            "",
            "import runpod",
            "",
            f'WORK_DIR = "/workspace/{name}"',
            'MODELS_DIR = Path(os.environ.get("MODELS_DIR", "/runpod-volume/models"))',
            "",
        ]

        # _ensure_models function
        if has_models:
            lines += self._ensure_models_lines(recipe)
        else:
            lines += [
                "def _ensure_models():",
                "    pass  # No models defined in this recipe",
                "",
            ]

        # handler function
        lines += [
            "",
            "def handler(job):",
            '    """RunPod serverless handler."""',
            '    inputs = job.get("input", {})',
            "",
        ]

        # Apply defaults
        for inp_name, spec in recipe.inputs.items():
            if spec.default is not None:
                lines.append(f"    {inp_name} = inputs.get({inp_name!r}, {spec.default!r})")
            else:
                lines.append(f"    {inp_name} = inputs.get({inp_name!r})")

        if recipe.inputs:
            lines.append("")

        # Validate required inputs
        required_inputs = [n for n, s in recipe.inputs.items() if s.required]
        if required_inputs:
            for inp_name in required_inputs:
                lines += [
                    f"    if {inp_name} is None:",
                    f'        return {{"error": "Required input \'{inp_name}\' is missing"}}',
                ]
            lines.append("")

        lines += [
            "    _ensure_models()",
            "",
            f"    _cmd = [sys.executable, f'{{WORK_DIR}}/{script}']",
        ]

        # Build CLI args from inputs
        for inp_name, spec in recipe.inputs.items():
            flag = arg_mapping.get(inp_name, inp_name.replace("_", "-"))
            if spec.type == "boolean":
                lines += [
                    f"    if {inp_name}:",
                    f"        _cmd += ['--{flag}']",
                ]
            else:
                lines += [
                    f"    if {inp_name} is not None:",
                    f"        _cmd += ['--{flag}', str({inp_name})]",
                ]

        lines += [
            "",
            "    result = subprocess.run(",
            "        _cmd, capture_output=True, text=True, cwd=WORK_DIR",
            "    )",
            "    if result.returncode != 0:",
            '        return {"error": result.stderr[-2000:]}',
            "",
            "    # Collect file outputs",
            "    outputs: dict = {}",
        ]

        # Collect outputs
        if recipe.outputs:
            lines += [
                "    import glob as _glob",
                "    from pathlib import Path as _Path",
            ]
            for out in recipe.outputs:
                path_pat = out.path or f"outputs/*.{out.type}"
                lines += [
                    f"    _files_{out.name} = sorted(_glob.glob(f'{{WORK_DIR}}/{path_pat}'))",
                    f"    if _files_{out.name}:",
                    f"        outputs[{out.name!r}] = _files_{out.name}[-1]",
                ]
        else:
            lines.append("    # No outputs defined in recipe")

        lines += [
            "    return {",
            '        "output": result.stdout,',
            '        "outputs": outputs,',
            "    }",
            "",
            "",
            'runpod.serverless.start({"handler": handler})',
        ]

        return "\n".join(lines) + "\n"

    def _ensure_models_lines(self, recipe: Recipe) -> list[str]:
        lines: list[str] = [
            "def _ensure_models():",
            "    MODELS_DIR.mkdir(parents=True, exist_ok=True)",
        ]

        for model in recipe.models:
            dest_expr = f"MODELS_DIR / {model.destination!r}"
            if model.source == "huggingface":
                lines += [
                    f"    # {model.name}",
                    "    try:",
                    "        from huggingface_hub import snapshot_download",
                    f"        _dest = {dest_expr}",
                    f"        if not _dest.exists():",
                    f"            snapshot_download(",
                    f"                repo_id={model.id!r},",
                    "                local_dir=_dest,",
                    "                ignore_patterns=['*.msgpack', '*.h5', 'flax_model*'],",
                    "            )",
                    "    except Exception as _e:",
                    f"        print(f'Warning: failed to download {model.id}: {{_e}}')",
                ]
            elif model.source == "url":
                lines += [
                    f"    # {model.name} (URL download)",
                    "    import urllib.request",
                    f"    _dest = {dest_expr} / Path({model.id!r}).name",
                    "    _dest.parent.mkdir(parents=True, exist_ok=True)",
                    "    if not _dest.exists():",
                    f"        urllib.request.urlretrieve({model.id!r}, _dest)",
                ]
            elif model.source == "civitai":
                lines += [
                    f"    # {model.name} (CivitAI)",
                    "    import urllib.request",
                    "    _token = os.environ.get('CIVITAI_TOKEN', '')",
                    "    _headers = {'Authorization': f'Bearer {_token}'} if _token else {}",
                    f"    _civitai_url = f'https://civitai.com/api/download/models/{model.id}'",
                    f"    _dest = {dest_expr} / '{model.name}.safetensors'",
                    "    _dest.parent.mkdir(parents=True, exist_ok=True)",
                    "    if not _dest.exists():",
                    "        _req = urllib.request.Request(_civitai_url, headers=_headers)",
                    "        with urllib.request.urlopen(_req) as _r, open(_dest, 'wb') as _f:",
                    "            _f.write(_r.read())",
                ]

        lines.append("")
        return lines


# ---------------------------------------------------------------------------
# RunPod backend
# ---------------------------------------------------------------------------

class RunPodBackend(AbstractBackend):
    """RunPod.io serverless compute backend.

    Generates a Dockerfile and handler.py for serverless endpoint deployment.
    The user builds a Docker image, pushes it, registers a RunPod serverless
    endpoint, then kdream submits jobs via the RunPod API.

    Workflow::

        # 1. Generate artifacts
        kdream runpod generate stable-diffusion-xl-base

        # 2. Build & push image
        cd ~/.kdream/cache/stable-diffusion-xl-base/runpod
        docker build -t myuser/stable-diffusion-xl-base:latest .
        docker push myuser/stable-diffusion-xl-base:latest

        # 3. Register endpoint at runpod.io, then run:
        kdream run stable-diffusion-xl-base --backend runpod \\
            --endpoint-id ep-xxxx --prompt "red panda"

    """

    name = "runpod"

    def __init__(
        self,
        api_key: str | None = None,
        endpoint_id: str | None = None,
        gpu_type: str = "NVIDIA GeForce RTX 3090",
        docker_image: str | None = None,
        terminate_after_run: bool = True,
        verbose: bool = False,
    ):
        self.api_key = api_key or os.environ.get("RUNPOD_API_KEY")
        self.endpoint_id = endpoint_id or os.environ.get("RUNPOD_ENDPOINT_ID")
        self.gpu_type = gpu_type
        self.docker_image = docker_image
        self.terminate_after_run = terminate_after_run
        self.verbose = verbose
        self._dockerfile_builder = DockerfileBuilder()
        self._handler_builder = HandlerBuilder()

    # ------------------------------------------------------------------
    # AbstractBackend interface
    # ------------------------------------------------------------------

    def install(
        self,
        recipe: Recipe,
        cache_dir: Path,
        force_reinstall: bool = False,
    ):
        """Generate Dockerfile and handler.py for a RunPod serverless endpoint.

        No network calls are made — artifacts are written to
        ``cache_dir/<name>/runpod/``.

        Returns:
            :class:`~kdream.core.runner.PackageInfo` with ``path`` pointing to
            the runpod artifacts directory.
        """
        from kdream.core.runner import PackageInfo

        pkg_dir = cache_dir / recipe.metadata.name
        runpod_dir = pkg_dir / "runpod"
        runpod_dir.mkdir(parents=True, exist_ok=True)

        dockerfile_path = runpod_dir / "Dockerfile"
        handler_path = runpod_dir / "handler.py"
        config_path = runpod_dir / "config.json"

        if dockerfile_path.exists() and not force_reinstall:
            console.print(
                f"  [dim]RunPod artifacts already generated: {runpod_dir}[/dim]\n"
                "  Use --force-reinstall to regenerate."
            )
        else:
            console.print(
                f"\n[bold][1/3][/bold] Generating Dockerfile for "
                f"[cyan]{recipe.metadata.name}[/cyan]…"
            )
            dockerfile_content = self._dockerfile_builder.build(recipe)
            dockerfile_path.write_text(dockerfile_content, encoding="utf-8")
            console.print(f"  [green]✓ Dockerfile saved:[/green] {dockerfile_path}")

            console.print(
                f"\n[bold][2/3][/bold] Generating handler.py for "
                f"[cyan]{recipe.metadata.name}[/cyan]…"
            )
            handler_content = self._handler_builder.build(recipe)
            handler_path.write_text(handler_content, encoding="utf-8")
            console.print(f"  [green]✓ handler.py saved:[/green] {handler_path}")

            console.print("\n[bold][3/3][/bold] Saving config.json…")
            config = {
                "recipe_name": recipe.metadata.name,
                "gpu_type": self.gpu_type,
                "docker_image": self.docker_image or f"<dockerhub-user>/{recipe.metadata.name}:latest",
                "endpoint_id": self.endpoint_id or "",
            }
            config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
            console.print(f"  [green]✓ config.json saved:[/green] {config_path}")

            self._print_instructions(recipe, runpod_dir)

        return PackageInfo(
            recipe_name=recipe.metadata.name,
            path=runpod_dir,
            ready=True,
            venv_path=runpod_dir,
            repo_path=runpod_dir,
            models_path=runpod_dir,
        )

    def run(self, package, inputs: dict[str, Any]) -> dict[str, Any]:
        """Submit a job to a RunPod serverless endpoint.

        Requires the endpoint to be registered and ``endpoint_id`` configured
        (either via constructor or ``RUNPOD_ENDPOINT_ID`` environment variable).

        Returns:
            Dict with keys ``output``, ``outputs``, and ``job_id``.
        """
        # Load config.json for endpoint_id if not already set
        config_path = package.path / "config.json"
        endpoint_id = self.endpoint_id
        if not endpoint_id and config_path.exists():
            config = json.loads(config_path.read_text(encoding="utf-8"))
            endpoint_id = config.get("endpoint_id") or None

        if not endpoint_id:
            raise BackendError(
                "No RunPod endpoint ID configured.\n\n"
                "To set up a serverless endpoint:\n"
                f"  1. cd {package.path}\n"
                f"  2. docker build -t <image> . && docker push <image>\n"
                "  3. Register endpoint at runpod.io → Serverless → New Endpoint\n"
                "  4. Re-run with: --endpoint-id <id>  or  RUNPOD_ENDPOINT_ID=<id>"
            )

        if not self.api_key:
            raise BackendError(
                "No RunPod API key configured. "
                "Set RUNPOD_API_KEY environment variable or pass api_key to RunPodBackend."
            )

        try:
            import runpod  # type: ignore[import]
        except ImportError:
            raise BackendError(
                "The 'runpod' package is required for the RunPod backend.\n"
                "Install it with: pip install 'kdream[runpod]'"
            )

        runpod.api_key = self.api_key
        endpoint = runpod.Endpoint(endpoint_id)

        try:
            result = endpoint.run_sync(inputs, timeout=300)
        except TimeoutError:
            raise BackendError(
                "RunPod job timed out after 300 seconds. "
                "Consider using async mode for long-running jobs."
            )
        except Exception as exc:
            raise BackendError(f"RunPod endpoint error: {exc}") from exc

        if isinstance(result, dict) and "error" in result:
            raise BackendError(f"RunPod job failed: {result['error']}")

        return result if isinstance(result, dict) else {"output": result, "outputs": {}}

    def is_installed(self, recipe_name: str, cache_dir: Path) -> bool:
        """Return True if Dockerfile has been generated for *recipe_name*."""
        return (cache_dir / recipe_name / "runpod" / "Dockerfile").exists()

    def generate_artifacts(
        self,
        recipe: Recipe,
        output_dir: Path | str | None = None,
        inputs: dict[str, Any] | None = None,
    ) -> Path:
        """Generate Dockerfile and handler.py to *output_dir*.

        Convenience method for use outside the install/run flow.

        Args:
            recipe:     Recipe to generate artifacts from.
            output_dir: Directory to write files (default: cwd).
            inputs:     Ignored (present for API symmetry with other backends).

        Returns:
            Path to the directory containing the generated artifacts.
        """
        dest = Path(output_dir) if output_dir else Path.cwd()
        dest.mkdir(parents=True, exist_ok=True)

        dockerfile_content = self._dockerfile_builder.build(recipe)
        (dest / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")

        handler_content = self._handler_builder.build(recipe)
        (dest / "handler.py").write_text(handler_content, encoding="utf-8")

        config = {
            "recipe_name": recipe.metadata.name,
            "gpu_type": self.gpu_type,
            "docker_image": self.docker_image or f"<dockerhub-user>/{recipe.metadata.name}:latest",
            "endpoint_id": self.endpoint_id or "",
        }
        (dest / "config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")

        return dest

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _print_instructions(self, recipe: Recipe, runpod_dir: Path) -> None:
        name = recipe.metadata.name
        img = self.docker_image or f"<dockerhub-user>/{name}:latest"
        console.print(Panel(
            textwrap.dedent(f"""\
                [bold]Next steps to deploy on RunPod:[/bold]

                [cyan]1.[/cyan] Build and push the Docker image:
                   cd {runpod_dir}
                   docker build -t {img} .
                   docker push {img}

                [cyan]2.[/cyan] Register a serverless endpoint:
                   Go to [link]https://www.runpod.io/console/serverless[/link]
                   → New Endpoint → use image: {img}
                   → Select GPU: {self.gpu_type}

                [cyan]3.[/cyan] Copy the Endpoint ID, then run:
                   kdream run {name} --backend runpod \\
                       --endpoint-id <id> --prompt "..."
                   # or: export RUNPOD_ENDPOINT_ID=<id>
            """),
            title="kdream RunPod",
            expand=False,
        ))
